baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Alessandro Baffa's weblog"
pagerSize = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ['html']
  section = ['html']

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = false
  highlightColor = "#e08320"
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#2b16ff"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"
  runningQuote = "Running is the greatest metaphor for life, because you get out of it what you put into it."
  techQuote = "The best way to predict the future is to invent it."

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = "running"
    name = "Running"
    url = "/tags/running/"
    weight = 2
  [[menu.main]]
    identifier = "tech"
    name = "Tech"
    url = "/tags/tech/"
    weight = 3
  [[menu.main]]
    name = "All"
    identifier = "blog"
    weight = 4
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 5
    url = "/About/"
