baseURL = "/"
languageCode = "en-us"
title = "Alessandro Baffa"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = "UA-114385313-1"

[author]
name = "Alessandro Baffa"

[params]
author = "Alessandro Baffa"
description = "Software Engineer and Solutions Architect."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "twitter"
url = "https://www.twitter.com/alebaffa"

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/alessandrobaffa"

[[params.social]]
id = "github"
url = "https://github.com/alebaffa"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2


[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
